### ISSUE TITLE
Build failed on Linux

### ISSUE THREAD

**Issue by bingen** [Y2Z/monolith#45]
I followed the instructions in the README file and I got the followting error:
```
(...)
   Compiling monolith v2.0.14 (/home/bingen/Downloads/monolith)
error[E0502]: cannot borrow `response` as mutable because it is also borrowed as immutable
  --> src/http.rs:64:13
   |
51 |         let final_url = response.url().as_str();
   |                         -------- immutable borrow occurs here
...
64 |             response.copy_to(&mut data)?;
   |             ^^^^^^^^ mutable borrow occurs here
...
81 |     }
   |     - immutable borrow ends here

error[E0502]: cannot borrow `response` as mutable because it is also borrowed as immutable
  --> src/http.rs:79:16
   |
51 |         let final_url = response.url().as_str();
   |                         -------- immutable borrow occurs here
...
79 |             Ok(response.text().unwrap())
   |                ^^^^^^^^ mutable borrow occurs here
80 |         }
81 |     }
   |     - immutable borrow ends here

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0502`.
error: failed to compile `monolith v2.0.14 (/home/bingen/Downloads/monolith)`, intermediate artifacts can be found at `/home/bingen/Downloads/monolith/target`

Caused by:
  Could not compile `monolith`.
``` 

I'm on a Debian based distro, using cargo 1.35.0 and using current `master` branch (commit fada788).

**Comment by bingen** [comment]
Cool, it worked now, thanks!

**Comment by radum** [comment]
1.34 fails for me, after upgrade to 1.37 works fine.

**Comment by uda** [comment]
Failed for me on `rustc 1.35` after upgrading to `1.36` (`1.36.0+dfsg1+llvm-2ubuntu1~18.04.1`) it compiled ok.

**Comment by vflyson** [comment]
Since it seems to be a bug in rustc =< 1.35, fixing it in the code and putting Rust 1.35 into the pipeline would be a rather bad practice of hiding symptoms. I'll keep this thread open so that people will know they have to do `rustup update` and use the latest stable version of Rust.
